apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: quickhire
type: Opaque
stringData:
  mongodb-root-password: mlcgjnwc9a
  mongodb-username: quickhire
  mongodb-password: mlcgjnwc9a