apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: quickhire
data:
  NODE_ENV: production
  PORT: "5000"
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: quickhire
  JWT_SECRET: "your-jwt-secret-change-in-production"
  CORS_ORIGIN: "http://<MASTER_IP>:3000"