apiVersion: v1
kind: Service
metadata:
  name: quickhire-frontend
  namespace: quickhire
spec:
  selector:
    app: quickhire-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
  type: NodePort